//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPPool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckAnswer()
        {
            this.UserCheckAnswers = new HashSet<UserCheckAnswer>();
        }
    
        public int ID { get; set; }
        public int Question_ID { get; set; }
        public string Answer { get; set; }
    
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCheckAnswer> UserCheckAnswers { get; set; }
    }
}
