//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPPool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoolEntities : DbContext
    {
        public PoolEntities()
            : base("name=PoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckAnswer> CheckAnswers { get; set; }
        public virtual DbSet<Pool> Pools { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserCheckAnswer> UserCheckAnswers { get; set; }
        public virtual DbSet<UserOpenAnswer> UserOpenAnswers { get; set; }
    }
}
